#!/usr/bin/perl

$|=1;

#
# "tee" to another process as well as stdout
#
$cmd = shift @ARGV;
@args = @ARGV;
map(s/"/\\"/g,@args);
map(s/^(.*)$/"$1"/,@args);
$cmd = join(" ",$cmd,@args);
print $cmd,"\n";

open(CMD,"|$cmd") or die "Error: Cannot execute command [$cmd]: $!\n";

while ($_ = <STDIN>) {
	print $_;
	print CMD $_;
}

close CMD;
exit $?>>8;
