####################################
# Makefile for hello world
###################################

# Test merge of specific commit

.PHONY: all clean

# main targets
all: helloworld

helloworld: helloworld.c
	gcc -o $@ $<

# Clean Targets
clean:
	rm -f helloworld
